services:
  db:
    image: postgres:16
    container_name: mockly_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mockly
    ports:
      - "5432:5432"
    volumes:
      - mockly_db_data:/var/lib/postgresql/data

volumes:
  mockly_db_data:
